### ISSUE TITLE
Text Widget Error after update dart 2.5.0:- Failed assertion: line 269 pos 10: 'data != null' for text.dart package

### ISSUE THREAD

**Issue by Tawfeekamr** [londonappbrewery/quizzler-flutter#3]
## Steps to Reproduce

Link to the Main code:

[main.dart](https://gist.github.com/Tawfeekamr/572414a1c24aab0bf0e2f16326fc6974
)
I'm working in windows10... 
1. After upgrade flutter and Dart to 2.5.0, I get an error that tells me text.dart has a problem.
2. I didn't import text.dart! it's come from Flutter widgets.
3. the screenshot
![image](https://user-images.githubusercontent.com/5726477/67441871-49827080-f607-11e9-8902-bae561c2ed70.png)

**Target Platform: Anroid 
**Target OS version/browser: Android 9
**Devices: Nexus 6

## Logs

[  +55 ms] I/flutter ( 7881): #390    _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
[   +2 ms] I/flutter ( 7881): #395    _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
[   +1 ms] I/flutter ( 7881): #396    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
[   +1 ms] I/flutter ( 7881): #397    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[   +2 ms] I/flutter ( 7881): (elided 6 frames from class _AssertionError and package dart:async)

```
```

```
```

[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\flutter
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\totos\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] VS Code (version 1.39.1)
    • VS Code at C:\Users\totos\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

```
```

**Comment by Tawfeekamr** [comment]
![image](https://user-images.githubusercontent.com/5726477/67477605-1b327e80-f663-11e9-9363-4b3867f5bb75.png)
I fixed the issue using this solution.

**Comment by ParsaRbn** [comment]
having same issue with iOS simulator

<img width="1680" alt="Screen Shot 2020-08-29 at 1 05 17 AM" src="https://user-images.githubusercontent.com/70341935/91612966-cbfc5f00-e993-11ea-9dc1-d12e33ddc428.png">

**Comment by fvaladares** [comment]
Hello,

I thought that Dart is null safe now, so you can't assign null to a
variable.

Take a look at line 360, as said in the console error message, the data
variable can't be null.

Regards.
---
*Fabrício G. Valadares*
Lattes: http://lattes.cnpq.br/1002632563427298
Mobile: +55 31 9 9357-6193
Linkedin:http://br.linkedin.com/pub/fabricio-valadares/45/586/5a1/
mail: fabricio.valadares@gmail.com

*Os homens conseguiriam muito mais coisas se julgassem menos coisas
impossíveis.*

Embora ninguém possa voltar atrás e fazer um novo começo, qualquer um pode
começar agora e fazer um novo fim. Francisco Cândido Xavier


The information contained in this email and any attachments is confidential
and may be subject to copyright or other intellectual property protection.
If you are not the intended recipient, you are not authorized to use or
disclose this information, and we request that you notify us by reply mail
or telephone and delete the original message from your mail system.
