### ISSUE TITLE
can not run the app

### ISSUE THREAD

**Issue by calystary** [londonappbrewery/quizzler-flutter#31]
when trying to run:
======== Exception caught by widgets library =======================================================
The following assertion was thrown building QuizPage(dirty, state: _QuizPageState#0c640):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 378 pos 10: 'data != null'

The relevant error-causing widget was: 
  QuizPage QuizPage:file:///C:/Users/lulu/Desktop/projects/angela/quizzler_flutter/lib/main.dart:16:20
When the exception was thrown, this was the stack: 
#2      new Text (package:flutter/src/widgets/text.dart:378:10)
#3      _QuizPageState.build (package:quizzler/main.dart:45:22)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#8      StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#14     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#20     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#24     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#28     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#32     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#34     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5787:32)
#35     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#38     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#40     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#44     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#47     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#49     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#55     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#62     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#65     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#67     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#71     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#75     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#78     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#80     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#84     ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#87     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#88     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#89     StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#90     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#91     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#95     StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#97     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#102    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#104    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#106    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#111    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#113    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#117    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#120    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#122    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#124    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#125    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#129    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#130    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#131    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#133    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#134    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#135    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#136    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#137    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#138    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#139    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#141    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#142    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#143    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#146    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#149    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#150    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#151    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#154    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#155    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#156    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#158    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#159    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#160    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#161    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#162    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#163    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#164    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#165    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#166    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#167    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#168    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#169    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#172    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#174    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#175    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#176    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#177    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#178    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#179    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#180    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#181    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#182    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#183    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#184    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#185    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#186    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#187    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#188    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#189    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)

**Comment by calystary** [comment]
didn't change nothing in the code, only wiped data in emulator, after that  started working,
